INSERT INTO hero (name, power) VALUES ('Spider-Man', 'throw webs');
INSERT INTO hero (name, power) VALUES ('Superman', 'Flight, superhuman strength, x-ray vision');
INSERT INTO hero (name, power) VALUES ('Ant-Man', 'Change body size');
INSERT INTO hero (name, power) VALUES ('Black Panther', 'Juices of the Heart-Shaped Herb');
INSERT INTO hero (name, power) VALUES ('Black Widow', 'Dangerous assassin');
INSERT INTO hero (name, power) VALUES ('Captain America', 'Super-Soldier');
INSERT INTO hero (name, power) VALUES ('Captain Marvel', 'Kree technology');
INSERT INTO hero (name, power) VALUES ('Cat-Woman', 'Hand-to-hand combat skills');
INSERT INTO hero (name, power) VALUES ('Doctor Strange', 'Magic');
INSERT INTO hero (name, power) VALUES ('Flash', 'Speed');
INSERT INTO hero (name, power) VALUES ('Iron Man', 'Iron armor');
INSERT INTO hero (name, power) VALUES ('Hulk', 'Super strength');
INSERT INTO hero (name, power) VALUES ('Thor', 'God of thunder');
INSERT INTO hero (name, power) VALUES ('Wonder Woman', 'Super strength');